version: "3"

services:
  empyrion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: empyrion_container
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD/gamedir_beta:/home/user/Steam
    network_mode: host
    restart: unless-stopped
